# Generated by Django 2.1.3 on 2018-11-26 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_remove_contact_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='company',
            field=models.CharField(default='self', max_length=100),
            preserve_default=False,
        ),
    ]
